### ISSUE TITLE
IStructuredDocumentRegion management failed.

### ISSUE THREAD

**Issue by jabby** [angelozerr/angularjs-eclipse#129]
Today I notice I have 2 exception in Error Log view. 

## First exception
I don't know when it happen.

	java.lang.StringIndexOutOfBoundsException: String index out of range: 13
		at java.lang.String.substring(String.java:1950)
		at org.eclipse.angularjs.core.utils.AngularRegionUtils.getAngularELRegion(AngularRegionUtils.java:66)
		at org.eclipse.angularjs.core.utils.AngularRegionUtils.getAngularELRegion(AngularRegionUtils.java:52)
		at org.eclipse.angularjs.internal.ui.hyperlink.HTMLAngularHyperLinkDetector.createHyperlinkForExpression(HTMLAngularHyperLinkDetector.java:177)
		at org.eclipse.angularjs.internal.ui.hyperlink.HTMLAngularHyperLinkDetector.detectHyperlinks(HTMLAngularHyperLinkDetector.java:154)
		at org.eclipse.ui.texteditor.HyperlinkDetectorRegistry$HyperlinkDetectorDelegate.detectHyperlinks(HyperlinkDetectorRegistry.java:80)
		at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:289)
		at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:261)
		at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:469)
		at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:212)
		at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
		at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
		at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
		at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
		at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
		at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
		at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
		at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
		at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
		at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
		at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
		at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
		at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
		at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
		at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
		at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
		at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
		at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
		at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:483)
		at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
		at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
		at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
		at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

## Second exception 
It appear when I edit html template and use the alt + arrow down shortcut in Eclipse. 

```html
<td>
	{{value.providerConfig.optionReference}}
</td>
<td>
	{{value.description | i18n:creationLanguage}}
</td>
```
In the previous code example use the "alt + arrow down" shortcut to move the first line at the bottom of the example.

	org.eclipse.wst.xml.core.internal.document.StructuredDocumentRegionManagementException: IStructuredDocumentRegion management failed.
		at org.eclipse.wst.xml.core.internal.document.XMLModelParser.removeStructuredDocumentRegion(XMLModelParser.java:2200)
		at org.eclipse.wst.xml.core.internal.document.XMLModelParser.replaceStructuredDocumentRegions(XMLModelParser.java:2339)
		at org.eclipse.wst.xml.core.internal.document.DOMModelImpl.nodesReplaced(DOMModelImpl.java:737)
		at org.eclipse.wst.sse.core.internal.text.BasicStructuredDocument._fireEvent(BasicStructuredDocument.java:600)
		at org.eclipse.wst.sse.core.internal.text.BasicStructuredDocument.fireStructuredDocumentEvent(BasicStructuredDocument.java:1198)
		at org.eclipse.wst.sse.core.internal.text.BasicStructuredDocument.internalReplaceText(BasicStructuredDocument.java:1979)
		at org.eclipse.wst.sse.core.internal.text.BasicStructuredDocument.replaceText(BasicStructuredDocument.java:2423)
		at org.eclipse.wst.sse.core.internal.text.BasicStructuredDocument.replaceText(BasicStructuredDocument.java:2408)
		at org.eclipse.wst.sse.core.internal.text.JobSafeStructuredDocument.access$2(JobSafeStructuredDocument.java:1)
		at org.eclipse.wst.sse.core.internal.text.JobSafeStructuredDocument$3.run(JobSafeStructuredDocument.java:141)
		at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
		at org.eclipse.wst.sse.ui.EditorExecutionContext.execute(EditorExecutionContext.java:149)
		at org.eclipse.wst.sse.core.internal.text.JobSafeStructuredDocument.replaceText(JobSafeStructuredDocument.java:144)
		at org.eclipse.wst.sse.core.internal.text.BasicStructuredDocument.replace(BasicStructuredDocument.java:2368)
		at org.eclipse.wst.sse.core.internal.text.JobSafeStructuredDocument.access$0(JobSafeStructuredDocument.java:1)
		at org.eclipse.wst.sse.core.internal.text.JobSafeStructuredDocument$1.run(JobSafeStructuredDocument.java:103)
		at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
		at org.eclipse.wst.sse.ui.EditorExecutionContext.execute(EditorExecutionContext.java:149)
		at org.eclipse.wst.sse.core.internal.text.JobSafeStructuredDocument.replace(JobSafeStructuredDocument.java:106)
		at org.eclipse.ui.texteditor.MoveLinesAction.runWithEvent(MoveLinesAction.java:359)
		at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:122)
		at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
		at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:483)
		at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
		at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
		at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
		at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
		at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
		at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
		at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
		at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
		at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
		at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
		at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
		at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
		at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
		at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
		at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
		at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1262)
		at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
		at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1085)
		at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1070)
		at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1112)
		at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1108)
		at org.eclipse.swt.widgets.Widget.wmSysKeyDown(Widget.java:2580)
		at org.eclipse.swt.widgets.Control.WM_SYSKEYDOWN(Control.java:5386)
		at org.eclipse.swt.widgets.Control.windowProc(Control.java:4689)
		at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:339)
		at org.eclipse.swt.widgets.Display.windowProc(Display.java:5023)
		at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
		at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2549)
		at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
		at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
		at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
		at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
		at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
		at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
		at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
		at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
		at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
		at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
		at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
		at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
		at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
		at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
		at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:483)
		at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
		at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
		at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
		at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by angelozerr** [comment]
@jabby can I close this issue?

**Comment by jabby** [comment]
Yes of course.
