### ISSUE TITLE
NullPointerException on Angular Explorer refresh

### ISSUE THREAD

**Issue by vrubezhny** [angelozerr/angularjs-eclipse#153]
That's what I've found in my log while I was playing with jboss-kitchensink-angularjs project and was trying to link a controller to template page (/jboss-kitchensink-angularjs/src/main/webapp/partials/home.html). At some point Angular Explorer became cleared of any content for some reason (I've probably changed the Include Path on the project), then I've stopped (pressed the "red-square" button) and then refreshed it. The following error has appeared in my log:

!ENTRY org.eclipse.ui 4 0 2015-05-20 02:57:58.743
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.SWT.error(SWT.java:4396)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:139)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3790)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3428)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1112)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:993)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.NullPointerException
	at org.eclipse.angularjs.internal.ui.views.AngularExplorerView$5.run(AngularExplorerView.java:474)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	... 24 more

**Comment by angelozerr** [comment]
@vrubezhny I have fixed a problem which disposed the tern project every time WTP validator started. In my case the NPE was dues to this case. Tell me if it fixes your problem too.

**Comment by vrubezhny** [comment]
@angelozerr Nope, it didn't help. NPE has gone, but Angular Explorer view became empty and it isn't refreshed when I'm switching between the editors and/or changing the Include Path on the project.

When I'm roll your change back it starts to work (but, off course, with NPE)

**Comment by angelozerr** [comment]
@vrubezhny please retry with my commit https://github.com/angelozerr/tern.java/commit/4cf62050fc0f98d178d9339793f4c6f47cc21bda

Now we are sure that JSDTCLassPathManager which translate JSDT Include Path -> Tern Script Path is registered even if completion is not executed. 

>  but Angular Explorer view became empty

This problem was for the first tern project which has an empty tern script path if you didn't execute completion before using Angular Explorer.

It exists again one problem if you stop the tern server from the Angular Explorer and you try refresh. modules tree item is empty, if you click on second time on refresh, modules tree item when it is opened displays the list of modules.

Tell me if it fixes your problem.

**Comment by vrubezhny** [comment]
@angelozerr Thanks.

It looks like the issue is fixed now.

**Comment by angelozerr** [comment]
Cool!
