### ISSUE TITLE
problematic package 'org.eclipse.angularjs.core' 0.10.0

### ISSUE THREAD

**Issue by paulvi** [angelozerr/angularjs-eclipse#163]
I use Enide 2015 (Mars), then updated tern.java only to latest SNAPSHOT, than noticed that context menu not rendered at first time and Error reported by Eclipse

I guess, it is because all of tern and angluar should of the same version.

The problematic package 'org.eclipse.angularjs.core' may originate in the following bundles:
  org.eclipse.angularjs.core 0.10.0.201506182210, from which the following bundles present on the stack trace import it:
    org.eclipse.angularjs.ui 0.10.0.201506182210

```
------
STATUS
------
pluginId            org.eclipse.ui.navigator
pluginVersion       3.6.0.v20150422-0725
code                2
severity            4
message             Problems occurred when invoking code from plug-in: "org.eclipse.ui.navigator".
fingerprint         70d341d1

Exception:java.lang.NoClassDefFoundError: org/eclipse/angularjs/core/AngularProject
	 at org.eclipse.angularjs.internal.ui.AngularNatureTester.testIsAngularProject(AngularNatureTester.java:51)
	 at org.eclipse.angularjs.internal.ui.AngularNatureTester.test(AngularNatureTester.java:42)
	 at org.eclipse.core.internal.expressions.Property.test(Property.java:58)
	 at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:100)
	 at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:53)
	 at org.eclipse.core.internal.expressions.AdaptExpression.evaluate(AdaptExpression.java:106)
	 at org.eclipse.ui.internal.dialogs.RegistryPageContributor.failsEnablement(RegistryPageContributor.java:305)
	 at org.eclipse.ui.internal.dialogs.RegistryPageContributor.isApplicableTo(RegistryPageContributor.java:247)
	 at org.eclipse.ui.internal.dialogs.PropertyPageContributorManager.getApplicableContributors(PropertyPageContributorManager.java:216)
	 at org.eclipse.ui.internal.dialogs.PropertyPageContributorManager.getApplicableContributors(PropertyPageContributorManager.java:235)
	 at org.eclipse.ui.dialogs.PropertyDialogAction.hasPropertyPagesFor(PropertyDialogAction.java:106)
	 at org.eclipse.ui.dialogs.PropertyDialogAction.isApplicableForSelection(PropertyDialogAction.java:148)
	 at org.eclipse.ui.dialogs.PropertyDialogAction.isApplicableForSelection(PropertyDialogAction.java:128)
	 at org.eclipse.ui.internal.navigator.resources.actions.PropertiesActionProvider.fillContextMenu(PropertiesActionProvider.java:63)
	 at org.eclipse.ui.navigator.NavigatorActionService$2.run(NavigatorActionService.java:225)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.ui.navigator.NavigatorActionService.addCommonActionProviderMenu(NavigatorActionService.java:219)
	 at org.eclipse.ui.navigator.NavigatorActionService.fillContextMenu(NavigatorActionService.java:174)
	 at org.eclipse.ui.navigator.CommonNavigatorManager.fillContextMenu(CommonNavigatorManager.java:267)
	 at org.eclipse.ui.navigator.CommonNavigatorManager$3.menuAboutToShow(CommonNavigatorManager.java:283)
	 at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:333)
	 at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:466)
	 at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:461)
	 at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:493)
	 at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:255)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1137)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1118)
	 at org.eclipse.swt.widgets.Control.WM_INITMENUPOPUP(Control.java:5023)
	 at org.eclipse.swt.widgets.Control.windowProc(Control.java:4691)
	 at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:339)
	 at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1633)
	 at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2117)
	 at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
	 at org.eclipse.swt.internal.win32.OS.TrackPopupMenu(OS.java:-2)
	 at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:262)
	 at org.eclipse.swt.widgets.Display.runPopups(Display.java:4221)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3763)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:497)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

------
REPORT
------
anonymousId         39a4162c-1c03-4119-a65e-f6895adad4e9
name                Paul Verest
email               paul.verest@live.com
comment             The problematic package 'org.eclipse.angularjs.core' may originate in the following bundles:
  org.eclipse.angularjs.core 0.10.0.201506182210, from which the following bundles present on the stack trace import it:
    org.eclipse.angularjs.ui 0.10.0.201506182210

eclipseBuildId      4.5.0.I20150603-2000
eclipseProduct      nodeclipse.package.enide.product
javaRuntimeVersion  1.8.0_45-b15
osgiWs              win32
osgiOs              Windows8
osgiOsVersion       6.2.0
osgiArch            x86_64
logMessage          false
ignoreSimilar       false

-------
BUNDLES
-------
name                org.eclipse.angularjs.ui
version             0.10.0.201506182210

name                org.eclipse.core.databinding.observable
version             1.5.0.v20150422-0725

name                org.eclipse.core.databinding
version             1.5.0.v20150422-0725

name                org.eclipse.core.expressions
version             3.5.0.v20150421-2214

name                org.eclipse.core.runtime
version             3.11.0.v20150405-1723

name                org.eclipse.e4.ui.workbench
version             1.3.0.v20150531-1948

name                org.eclipse.e4.ui.workbench.swt
version             0.13.0.v20150504-0621

name                org.eclipse.equinox.app
version             1.3.300.v20150423-1356

name                org.eclipse.equinox.launcher
version             1.3.100.v20150511-1540

name                org.eclipse.jface
version             3.11.0.v20150602-1400

name                org.eclipse.swt
version             3.104.0.v20150528-0211

name                org.eclipse.ui
version             3.107.0.v20150507-1945

name                org.eclipse.ui.ide.application
version             1.1.0.v20150422-0725

name                org.eclipse.ui.ide
version             3.11.0.v20150510-1749

name                org.eclipse.ui.navigator
version             3.6.0.v20150422-0725

name                org.eclipse.ui.navigator.resources
version             3.5.0.v20150422-0725

```

**Comment by angelozerr** [comment]
@paulvi , I'm sorry, but I don't understand what you expect?

**Comment by paulvi** [comment]
nothing so far, just letting know you about weirdness.

If 1.x should not work with 0.10, then just close this

**Comment by angelozerr** [comment]
To be honnest with you, I don't know and I have no time to check if some version works with other version. The best thing is to align tern.java & AngularJS Eclipse versions.
