### ISSUE TITLE
Angularjs eclipse plugin - modules not listed

### ISSUE THREAD

**Issue by ckasap** [angelozerr/angularjs-eclipse#196]
Hi ,

I am behind corporate proxy and trying to use the plugin.  

My problem is intellisense is not working. I have read many tutorials for plugin installation but none of them is adressing the issue...

I think the problem is that the modules are not listed. 

![pic](https://cloud.githubusercontent.com/assets/5550814/15073354/b28c872e-13a1-11e6-90ab-405ffb2d5ef5.png)

Most likely a proxy error but I do not see them in logs...

A related error may be this : 

tern.TernException: Cannot find tern node.js server at D:\programs\eclipse-jee-mars-2-win32-x86_64\eclipse\plugins\ternjs_1.1.0.201511082254.jar\node_modules\tern\bin\tern
	at tern.server.nodejs.process.internal.NodejsProcess.getNodejsTernFile(NodejsProcess.java:172)
	at tern.server.nodejs.process.internal.NodejsProcess.<init>(NodejsProcess.java:153)
	at tern.server.nodejs.process.NodejsProcessManager.create(NodejsProcessManager.java:124)
	at tern.server.nodejs.NodejsTernServer.<init>(NodejsTernServer.java:97)
	at tern.eclipse.ide.server.nodejs.internal.core.TernNodejsServerFactory.create(TernNodejsServerFactory.java:54)
	at tern.eclipse.ide.internal.core.TernServerType.createServer(TernServerType.java:90)
	at tern.eclipse.ide.internal.core.resources.IDETernProject.getTernServer(IDETernProject.java:161)
	at tern.resources.TernFileSynchronizer.ensureSynchronized(TernFileSynchronizer.java:160)
	at tern.eclipse.ide.internal.ui.EditorActivationTracker$2.run(EditorActivationTracker.java:85)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

I change the tern server to native node.js server but this does not help either

**Comment by angelozerr** [comment]
It seems that your ternjs plugin (which contains tern plugin)is not installed correctly? Check you have a ternjs* folder in your Eclipse HOME.

It seems  D:\programs\eclipse-jee-mars-2-win32-x86_64\eclipse\plugins\ternjs_1.1.0.201511082254.jar should hosts the same files than https://github.com/angelozerr/tern.java/tree/master/core/ternjs
