### ISSUE TITLE
Path must be a String. Received undefined

### ISSUE THREAD

**Issue by hemantkrbajaj** [angelozerr/angularjs-eclipse#199]
Hi team i am facing the below issue while running the protractor test with eclipse:
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at C:\Users\Hemant Bajaj\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\safari.js:84:29
    at Object.<anonymous> (C:\Users\Hemant Bajaj\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\safari.js:98:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

Test.js : 
describe('angularjs homepage todo list', function(){
	it('should add a todo', function() {
		browser.get('http://www.angularjs.org');
	element(by.model('todotext')).sendKeys('write a protractor test');
	});
});

config.js :
exports.config = {
		directConnect: true,
		//seleniumAddress: 'http://localhost:4444/wd/hub',
		browserName: 'chrome',
		specs: ['Test.js']
};

both files present at same location.

Environment:
Windows 10 
Eclipse Kepler
AngularJS 1.2.0 -Snapshot plugin
NodeJsEclipse Plugin.

Please help.
Thanks!!
Hemant

**Comment by angelozerr** [comment]
I'm not a big expert with protractor. Have you the same problem when you start protractor without eclipse?

**Comment by hemantkrbajaj** [comment]
@angelozerr  No, it worked with the command prompt.

**Comment by angelozerr** [comment]
@hemantkrbajaj I have no time to study the problem today.

**Comment by bhreinb** [comment]
Hello there,

This would seem to be an issue for me too. I believe it to be eclipse related. I get the exact same error @hemantkrbajaj  mentions above

path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at C:\Users\bxb145\workspace\Sample\node_modules\selenium-webdriver\safari.js:84:29
    at Object.<anonymous> (C:\Users\bxb145\workspace\Sample\node_modules\selenium-webdriver\safari.js:98:3)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

I cloned the exact same project to webstorm and I'm able to run  the project every time. Let me know if you need any more help on reproducing this? I'm also able to run the project outside of eclipse too from the command line.

**Comment by santhosh12992** [comment]
Even i am also facing exactly the same issue. Fingers crossed...

**Comment by lnallan** [comment]
I am facing the same issue too....with nodeclipse debugger and enide IDE
