### ISSUE TITLE
Trying to install getting error

### ISSUE THREAD

**Issue by DivyaGN** [angelozerr/angularjs-eclipse#209]
Hi , 
I tried installing angularjs-eclipse using both 
http://oss.opensagres.fr/angularjs-eclipse/1.2.0/
http:///oss.opensagres.fr/angularjs-eclipse/1.3.0/
getting the below error
An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://oss.opensagres.fr/tern.repository/1.2.0/plugins/tern.websocket.provider_1.2.0.201606160856.jar.
Premature end of Content-Length delimited message body (expected: 794013; received: 399200
Unable to read repository at http://oss.opensagres.fr/tern.repository/1.2.0/plugins/ternjs_1.2.0.201606160856.jar.
Read timed out

my eclipse version is :  Mars.2 Release (4.5.2)

org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 1000888; received: 336271
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer$1.performFileTransfer(AbstractRetrieveFileTransfer.java:178)
	at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:73)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by angelozerr** [comment]
Same issue than https://github.com/angelozerr/angularjs-eclipse/issues
